### PR TITLE
v0.2.2

### PR DESCRIPTION
**Pull request by dpark6060**
Added subject to config

### CODE REVIEW

**Review by pvelasco — COMMENTED** [review]
Any reason why we didn't published `0.2.1`?

**Comment by dpark6060** [comment]
We skipped 0.2.1 because The docker image failed and it was easier for me to fix and bump than try to rebuild... D:

**Comment by pvelasco** [comment]
LGTM

**Review by pvelasco — APPROVED** [review]
LGTM

**Pull request merged**
