### PR TITLE
Remove redundant gear versions

### PR DESCRIPTION
**Pull request by gsfr**
In preparation for docker image-based gears, we need to get rid of any redundant manifest versions, that shouldn't have been there in the first place. This is my proposal. Most of the deleted manifests are demo gears and thus of little relevance. dtiinit and hcp-struct need to be looked at more closely.

@tcbtcb Please work with @lmperry to estimate impact beyond vista lab and our dev server.

### CODE REVIEW

**Comment by gsfr** [comment]
@lmperry I just reviewed the remaining gear list, and we still have a number of manifests that don't point back to a docker hub tag. Would be good to get those fixed.

```
"docker-image": "scitran/afq"
"name": "afq",
"version": "0.0.2"

"docker-image": "flywheel/afq-demo"
"name": "afq-demo",
"version": "0.1.0"

"docker-image": "scitran/apply-canonical-xform"
"name": "apply-canonical-xform",
"version": "0.1.0"

"docker-image": "scitran/dcm2niix"
"name": "dcm2niix",
"version": "0.0.3"

"docker-image": "scitran/dicom-mr-classifier"
"name": "dicom-mr-classifier",
"version": "0.1.6"

"docker-image": "scitran/dtiinit"
"name": "dtiinit",
"version": "0.1.2"

"docker-image": "flywheel/example-gear"
"name": "flywheel-example-gear",
"version": "0.0.2"

"docker-image": "scitran/fsl-bet"
"name": "fsl-bet",
"version": "0.0.6"

"docker-image": "scitran/fsl-fast"
"name": "fsl-fast",
"version": "0.0.7"

"docker-image": "scitran/hdft-subsampled-recon"
"name": "hdft-subsampled-recon",
"version": "0.0.1"

"docker-image": "scitran/parrec-mr-classifier"
"name": "parrec-mr-classifier",
"version": "0.0.3"

"docker-image": "scitran/qa-dtiprep"
"name": "qa-dtiprep",
"version": "0.0.2"

"docker-image": "scitran/qa-report-fmri"
"name": "qa-report-fmri",
"version": "0.1.6"

"docker-image": "flywheel/reconall-demo"
"name": "reconall-demo",
"version": "0.0.2"

"docker-image": "scitran/structural-analysis"
"name": "structural-analysis",
"version": "0.0.1"
```

**Comment by tcbtcb** [comment]
Is the question 'Can we get rid of these without breaking anything in the wild?' or 'Do we need to make sure all of these have dockerhub images before removing them, and how much work would that take?'

**Comment by gsfr** [comment]
Yup, the question is, 'Can we get rid of these without breaking anything in the wild?'

This PR gets the Exchange to a fully coherent state. I do not expect having to do this again in the future.

**Comment by tcbtcb** [comment]
In the highly, highly unlikely event this impacts something in the wild, we should have upgraded that gear anyway, so that shouldn't stop us from doing anything.

**Comment by ryansanford** [comment]
Alternate approach could be to push docker images from the gear tarballs, tagged appropriately, then update the manifests here to reflect that. Just making that option known, not lobbying for it. I trust Thad on risk.

**Pull request merged**
