### PR TITLE
GEAR-4867 exchange cleanup

### PR DESCRIPTION
**Pull request by NPann**
* add `remove-gears.py` python script to remove gear from the exchange
* remove all deprecated gears. Namely:

  - acpc-anat
  - afni-brain-warp
  - afq
  - afq-pipeline
  - afq-pipeline-sdk
  - all-subject-bids-fmriprep
  - apply-canonical-xform
  - bruker2nifti
  - bxh-xcede-tools-qa
  - dcm-convert
  - dcm2nii
  - debug-generatefile
  - dti-error
  - dwi-flip-bvec
  - dwi-split-shells
  - eeg-classifier
  - flaudit
  - floc
  - flywheel-example-gear
  - fmriprep
  - fsl-fslhd
  - fslmerge
  - fw-test-analysis
  - fw-test-utility
  - hcp-diff
  - hcp-func
  - hcp-icafix
  - hcp-struct
  - hdft-subsampled-recon
  - mri-deface
  - ndmg
  - parrec-mr-classifier
  - qa-dtiprep
  - quicknat-gear
  - retinotopy-templates
  - structural-analysis
  - task-tsv-converter

### CODE REVIEW

**Comment by pvelasco** [comment]
It looks like the filtering of the manifests is not working (e.g., if the gear name is `bids-fmriprep`, it will also find manifests corresponding to the gear `all-subjects-bids-fmriprep`).

Perhaps after getting the `gear_json` you need to retrieve its parent folder, and add it to the filter for the manifests.

**Comment by NPann** [comment]
@pvelasco - Thanks Pablo. Big miss on my end. Updated the regex in that remove-gear.py adding the parent folder (I could not go directly with you solution as we have cases where the gear manifest got removed from the gears folder but not from the manifests ones)

**Comment by pvelasco** [comment]
LGTM!

**Review by pvelasco — APPROVED** [review]
LGTM

**Pull request merged**
