### PR TITLE
flywheel/breast-density-classifier:0.1.8

### PR DESCRIPTION
**Pull request by mpsampat**
@NPann could you please approve this small MR ?

### CODE REVIEW

**Comment by NPann** [comment]
@mehulsampat - it is so small that there is no file change here 😅

**Comment by mpsampat** [comment]
@NPann I committed twice maybe thus not showing ? checking it now

**Comment by mpsampat** [comment]
@NPann maybe i did not copy it correctly . checking it

**Comment by mpsampat** [comment]
@NPann sorry fixed now. just waiting for Travis CI to finish. will ping you when it is done

**Review by NPann — APPROVED** [review]

**Comment by mpsampat** [comment]
@NPann just fyi. i updated to use the latest 
https://gitlab.com/flywheel-io/tools/etc/qa-ci and `flywheel-io/scientific-solutions/etc/sse-qa-ci`
these changes make the formatting changes in manifest.json

**Pull request merged**
